### ISSUE TITLE
폴더 사라짐

### ISSUE THREAD

**Issue by JooYoungNoh** [APP-iOS3rd/PJ2T6_CleanArea#23]
StartView 폴더랑 안에 있는 파일들 다 사라져서 빨간색 됬어요
develop 브랜치에도 파일 없어서 파일 추가 안하시고 push 한 걸 merge 한 것 같습니다.

<img width="295" alt="스크린샷 2023-12-07 오후 6 13 26" src="https://github.com/APP-iOS3rd/PJ2T6_CleanArea/assets/96951827/4a72aa65-1c74-4df5-8adc-ae14a393afa7">

**Comment by JooYoungNoh** [comment]
지훈님 develop 브랜치 pull 받으시면 start 폴더 파일 있나요?

**Comment by Jihunkim95** [comment]
아녀 현재 develop 브랜치 버전에서는 start 파일이 삭제된 상태기 때문에 없어요. 그렇기 때문에 start 파일 삭제하신분이 다시 commit 하시거나,
급하시다면 이전 develop 브랜치에 checkout하셔서 start파일을 확인하면 될것 같아요 !

**Comment by hamfan524** [comment]
StartView는 민호님이 수정하신 부분인거같은데 Commit하고 push할때 무슨 이유인지 안올라간거같아요. 
급하다면, 깃 로그를 확인한 후 민호님 커밋 이전으로 되돌려서 다시 푸쉬를 하거나, 민호님이 확인 후 다시 푸쉬를 해주는 방법으로 해결해야 할거 같습니다.

**Comment by funMango** [comment]
늦게 확인해서 죄송합니다 ㅜㅜ
제가 다시 start파일 올려서 develop에 merge 하겠습니다!

**Comment by funMango** [comment]
해당 폴더 pull request 요청 했습니다.
accept 부탁드립니다!

**Comment by JooYoungNoh** [comment]
확인 했습니다~
