### ISSUE TITLE
검색기능 문제

### ISSUE THREAD

**Issue by funMango** [APP-iOS3rd/PJ2T6_CleanArea#60]
- 주거지, 취업여부, 학력, 나이까지 다 입력하고 나면 정책 개수가 거의 없습니다.
필터기준을 다시 정할 필요가 있다고 생각합니다.

- 전체선택과 제한없음 검색결과가 달라서 하나를 없애는 방향으로 논의해봐야 할거 같습니다.

**Comment by Jihunkim95** [comment]
- [x]  IOS 취업상태, 학력 “제한없음” 삭제 및 Server에서 어떤 부분을 선택했어도 “제한없음”포함되게 수정
- [x]  나이 입력시 나이에 맞는 정책 수정 및 추가
로 변경했습니다 ㅎ
